In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# the ruling party of each year from 1993 to 2007. 
# D stands for Democratic Party, R is for Republican Party
ruling_party={
    1993:"D",
    1994:"D",
    1995:"D",
    1996:"D",
    1997:"D",
    1998:"D",
    1999:"D",
    2000:"D",
    2001:"R",
    2002:"R",
    2003:"R",
    2004:"R",
    2005:"R",
    2006:"R",
    2007:"D",
}


# The Reald GDP in unit of million dollars of each state from year 1998 to 2007
## these data is extracted from BEA.gov.
state_gdp={
    "Kansas":{
        1998:108183.6,
        1999:111005.5,
        2000:114030.5,
        2001:114327.7,
        2002:116195,
        2003:118192.5,
        2004:119391.6,
        2005:123949.8,
        2006:130364.5,
        2007:137093.6
    },
    "Montana":{
        1998:30342.4,
        1999:30461.3,
        2000:31241.1,
        2001:31532.6,
        2002:32503.7,
        2003:33810.5,
        2004:35528.6,
        2005:37373.9,
        2006:38577.6,
        2007:40438.3
    },
    "Oklahoma":{
        1998:117596,
        1999:119685.4,
        2000:124227.6,
        2001:128891.2,
        2002:131293.3,
        2003:133417.2,
        2004:138096.8,
        2005:143471.1,
        2006:152857.7,
        2007:156219.5
    },
    "Texas":{
        1998:925556.7,
        1999:961513.2,
        2000:995661.2,
        2001:1020537.8,
        2002:1043566.9,
        2003:1050609.4,
        2004:1109477,
        2005:1141373.7,
        2006:1228547.3,
        2007:1286192.7
    },
    "Washington":{
        1998:288206.9,
        1999:308949.5,
        2000:311209.9,
        2001:303673.8,
        2002:307583.2,
        2003:312556.4,
        2004:319848.9,
        2005:340428,
        2006:353263.5,
        2007:373180.6
    }

}

print(ruling_party[2005])
print(state_gdp["WASHINGTON".title()][1999])

R
308949.5

In [ ]:
df = pd.read_csv("./drive/MyDrive/colab_notebooks/ECS_289L/project3/data/ML-TABLESML-table-weekly.csv", sep=",", header=0)
print(len(df))
df = df.loc[(df['year'] >= 1998) & (df['year'] <= 2007)]
len(df)

6094

4006

In [ ]:
### add column for each row
df['ruling_party'] = -1
df['gdp']=0
df

,year,state_name,county_name,yield,nutr_ret_high,suit_irrig_high_soy,AEZ_1,AEZ_2,AEZ_3,AEZ_4,...,week_51__EVPTRNS,week_51__ALLSKY_SFC_PAR_TOT,week_52__T2M_MAX,week_52__T2M_MIN,week_52__PRECTOTCORR,week_52__GWETROOT,week_52__EVPTRNS,week_52__ALLSKY_SFC_PAR_TOT,ruling_party,gdp
0,2007,KANSAS,CHEYENNE,47.0,10,10000,0,0,0,0,...,0.001429,242.19,0.300000,-6.920000,0.00,0.340000,0.000000,48.71,-1,0
1,2006,KANSAS,CHEYENNE,20.0,10,10000,0,0,0,0,...,0.001429,176.88,1.858571,-6.587143,19.23,0.358571,0.000000,188.20,-1,0
2,2005,KANSAS,CHEYENNE,21.0,10,10000,0,0,0,0,...,0.011429,286.00,13.358333,0.613333,0.05,0.340000,0.018333,259.97,-1,0
3,2004,KANSAS,CHEYENNE,18.0,10,10000,0,0,0,0,...,0.007143,246.21,10.962000,-0.012000,0.00,0.340000,0.008000,200.56,-1,0
4,2003,KANSAS,CHEYENNE,32.0,10,10000,0,0,0,0,...,0.001429,304.01,8.036667,-4.350000,0.00,0.290000,0.000000,127.53,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6084,2001,TEXAS,ZAVALA,27.3,10,5556,1,0,0,0,...,0.034286,503.50,11.330000,-1.290000,0.00,0.620000,0.010000,53.20,-1,0
6085,2000,TEXAS,ZAVALA,14.4,10,5556,1,0,0,0,...,0.174286,411.00,13.977143,0.895714,9.70,0.694286,0.091429,352.50,-1,0
6086,1999,TEXAS,ZAVALA,22.3,10,5556,1,0,0,0,...,0.000000,205.80,23.736000,6.522000,0.25,0.600000,0.000000,365.60,-1,0
6087,1998,TEXAS,ZAVALA,26.3,10,5556,1,0,0,0,...,0.041429,336.50,21.325000,4.742500,0.62,0.642500,0.110000,256.90,-1,0
6093,2006,TEXAS,WILLACY,24.0,10,7778,1,0,0,0,...,0.190000,309.60,20.861429,11.898571,0.61,0.417143,0.368571,448.08,-1,0

In [ ]:
a = df['state_name'].unique()
print(a)
br= ['KANSAS','MONTANA', 'WASHINGTON', 'OKLAHOMA', 'TEXAS']
for item in br:
  print(item.title())

['KANSAS' 'MONTANA' 'WASHINGTON' 'OKLAHOMA' 'TEXAS']
Kansas
Montana
Washington
Oklahoma
Texas

In [ ]:
party_failed=[]
for idx,row in df.iterrows():
  year = row['year']
  party = ruling_party[year]

  if party=="D":
    party=0
  elif party == "R":
    party=1

  df.at[idx,'ruling_party'] = party

  
  state = row['state_name'].title()
  df.at[idx,'gdp'] = state_gdp[state][1999]

In [ ]:
df

,year,state_name,county_name,yield,nutr_ret_high,suit_irrig_high_soy,AEZ_1,AEZ_2,AEZ_3,AEZ_4,...,week_51__EVPTRNS,week_51__ALLSKY_SFC_PAR_TOT,week_52__T2M_MAX,week_52__T2M_MIN,week_52__PRECTOTCORR,week_52__GWETROOT,week_52__EVPTRNS,week_52__ALLSKY_SFC_PAR_TOT,ruling_party,gdp
0,2007,KANSAS,CHEYENNE,47.0,10,10000,0,0,0,0,...,0.001429,242.19,0.300000,-6.920000,0.00,0.340000,0.000000,48.71,0,111005.5
1,2006,KANSAS,CHEYENNE,20.0,10,10000,0,0,0,0,...,0.001429,176.88,1.858571,-6.587143,19.23,0.358571,0.000000,188.20,1,111005.5
2,2005,KANSAS,CHEYENNE,21.0,10,10000,0,0,0,0,...,0.011429,286.00,13.358333,0.613333,0.05,0.340000,0.018333,259.97,1,111005.5
3,2004,KANSAS,CHEYENNE,18.0,10,10000,0,0,0,0,...,0.007143,246.21,10.962000,-0.012000,0.00,0.340000,0.008000,200.56,1,111005.5
4,2003,KANSAS,CHEYENNE,32.0,10,10000,0,0,0,0,...,0.001429,304.01,8.036667,-4.350000,0.00,0.290000,0.000000,127.53,1,111005.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6084,2001,TEXAS,ZAVALA,27.3,10,5556,1,0,0,0,...,0.034286,503.50,11.330000,-1.290000,0.00,0.620000,0.010000,53.20,1,961513.2
6085,2000,TEXAS,ZAVALA,14.4,10,5556,1,0,0,0,...,0.174286,411.00,13.977143,0.895714,9.70,0.694286,0.091429,352.50,0,961513.2
6086,1999,TEXAS,ZAVALA,22.3,10,5556,1,0,0,0,...,0.000000,205.80,23.736000,6.522000,0.25,0.600000,0.000000,365.60,0,961513.2
6087,1998,TEXAS,ZAVALA,26.3,10,5556,1,0,0,0,...,0.041429,336.50,21.325000,4.742500,0.62,0.642500,0.110000,256.90,0,961513.2
6093,2006,TEXAS,WILLACY,24.0,10,7778,1,0,0,0,...,0.190000,309.60,20.861429,11.898571,0.61,0.417143,0.368571,448.08,1,961513.2

In [ ]:
### write new df to a csv file
df.to_csv("./drive/MyDrive/colab_notebooks/ECS_289L/project3/data/ML-TABLESML-table-weekly_advanced_98_07.csv", index=None, sep=',')